language: cpp

compiler :
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsuitesparse-dev gfortran
  - sudo sed -i '/read dummy/d' `type -p gettextize`
  - sudo sed -i '/Press Return/d' `type -p gettextize`

script:
  - gettextize -f --no-changelog && sed -i 's#po/Makefile.in po/Makefile.in#po/Makefile.in#g' configure.ac && sed -i 's/config.rpath  config.rpath/config.rpath/g' Makefile.am && cd po && patch < ../diff-po-Makevars.template.patch && cd .. && mv po/Makevars.template po/Makevars && rm -f po/POTFILES.in && find src/libeurocode -name "*.cpp" > po/POTFILES.in && find src/libundo -maxdepth 1 -name "*.cpp" >> po/POTFILES.in && autoheader && aclocal -I m4 && libtoolize && automake --add-missing --copy && autoconf
  - ./configure --with-gui=none --with-debug --prefix=/usr/local CFLAGS="" CXXFLAGS="" && sed -i 's/-DPIC/-DPIC -Wl,--as-needed/g' libtool && find . -name "Makefile" -exec sed -i "s#-I/usr#-isystem/usr#g" {} \; && make && make check && make distcheck && make clean
  - ./configure --with-gui=none --with-debug --prefix=/usr/local CFLAGS="" CXXFLAGS="" CC=clang CXX=clang++ && sed -i 's/-DPIC/-DPIC -Wl,--as-needed/g' libtool && find . -name "Makefile" -exec sed -i "s#-I/usr#-isystem/usr#g" {} \; && make && make check && make distcheck && make clean
  - make clean && scan-build make

branches:
  only:
    - master

os:
  - linux
