language: cpp

compiler :
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsuitesparse-dev gfortran
  - sudo sed -i '/read dummy/d' `type -p gettextize`
  - sudo sed -i '/Press Return/d' `type -p gettextize`

script:
  - gettextize -f --no-changelog || die
  - sed -i 's#po/Makefile.in po/Makefile.in#po/Makefile.in#g' configure.ac || die
  - sed -i 's/config.rpath  config.rpath/config.rpath/g' Makefile.am || die
  - cd po || die
  - patch < ../diff-po-Makevars.template.patch || die
  - cd .. || die
  - mv po/Makevars.template po/Makevars || die
  - rm -f po/POTFILES.in || die
  - find src/test -name "*.cpp" > po/POTFILES.in || die
  - find src/lib -maxdepth 1 -name "*.cpp" >> po/POTFILES.in || die
  - autoheader || die
  - aclocal -I m4 || die
  - libtoolize || die
  - automake --add-missing --copy || die
  - autoconf || die
  - ./configure --with-gui=none --with-debug --prefix=/usr/local CFLAGS="" CXXFLAGS="" || die
  - sed -i 's/-DPIC/-DPIC -Wl,--as-needed/g' libtool || die
  - find . -name "Makefile" -exec sed -i "s#-I/usr#-isystem/usr#g" {} \; || die
  - make -j4 || die
  - make check -j4 || cat src/test/scenarii/action2.log
  - make distcheck -j4 || die

branches:
  only:
    - master

os:
  - linux
