language: cpp

compiler :
  - gcc
  - # clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsuitesparse-dev
  - sudo sed '/read dummy/d' /usr/bin/gettextize
  - sudo sed '/Press Return/d' /usr/bin/gettextize

script:
  gettextize -f --no-changelog
  sed -i 's#po/Makefile.in po/Makefile.in#po/Makefile.in#g' configure.ac
  sed -i 's/config.rpath  config.rpath/config.rpath/g' Makefile.am
  cd po
  patch < ../diff-po-Makevars.template.patch
  cd ..
  mv po/Makevars.template po/Makevars
  rm -f po/POTFILES.in
  find src/test -name "*.cpp" > po/POTFILES.in
  find src/lib -maxdepth 1 -name "*.cpp" >> po/POTFILES.in
  autoheader
  aclocal -I m4
  libtoolize
  automake --add-missing --copy
  autoconf
  ./configure --with-gui=gtk3 --with-debug --prefix=/usr/local CFLAGS="" CXXFLAGS=""
  sed -i 's/-DPIC/-DPIC -Wl,--as-needed/g' libtool
  find . -name "Makefile" -exec sed -i "s#-I/usr#-isystem/usr#g" {} \;
  make check -j9

branches:
  only:
    - master

os:
  - linux
