language: cpp

compiler :
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsuitesparse-dev gfortran
  - sudo sed -i '/read dummy/d' `type -p gettextize`
  - sudo sed -i '/Press Return/d' `type -p gettextize`

script: ./.travis.sh

branches:
  only:
    - master

os:
  - linux
