language: cpp
sudo: false

compiler :
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsuitesparse-dev
      - gfortran
      - cppcheck
      - clang

script: ./.travis.sh

branches:
  only:
    - master

os:
  - linux
